// Isolated logic verification: no browser navigation, no visual claim.
import fs from 'node:fs/promises';import vm from 'node:vm';import path from 'node:path';import {fileURLToPath} from 'node:url';import {performance} from 'node:perf_hooks';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),html=await fs.readFile(path.join(root,'docs/workpaper/案件事实底稿.html'),'utf8'),data=JSON.parse(html.match(/<script id="case-data" type="application\/json">([\s\S]*?)<\/script>/)[1]),script=html.match(/<script>\s*([\s\S]*?)<\/script>/)[1];
let printed=0;const nodes=new Map(),listeners=new Map();class Element{constructor(id){this.id=id;this.innerHTML='';this.textContent='';this.value='';this.hidden=false;this.events={};this.dataset={};this.classList={toggle:()=>{},add:()=>{},remove:()=>{}};this.style={}}addEventListener(k,fn){this.events[k]=fn}setAttribute(k,v){this[k]=v}scrollIntoView(){}querySelector(){return {currentTime:0,play:()=>Promise.resolve()}}}
const el=id=>{if(!nodes.has(id))nodes.set(id,new Element(id));return nodes.get(id)};
function run(d,{storage,mobile=false}={}){nodes.clear();listeners.clear();el('case-data').textContent=JSON.stringify(d);const c=vm.createContext({document:{documentElement:el('document-root'),getElementById:el,querySelectorAll:()=>[],addEventListener:(k,f)=>listeners.set(k,f),body:{style:{}}},window:{localStorage:storage,addEventListener:(k,f)=>listeners.set('window:'+k,f),print:()=>printed++},history:{replaceState:()=>{}},location:{hash:''},matchMedia:()=>({matches:mobile}),console});vm.runInContext(script,c,{timeout:2000});return c}
const logicData=JSON.parse(JSON.stringify(data));logicData.subjects[0].aliases.push('别称检索测试');
const c=run(logicData),results=[];function check(name,ok){if(!ok)throw Error(name);results.push(name)}
const read=code=>vm.runInContext(code,c,{timeout:2000});check('默认事实数量一致',read('filtered().length')===data.facts.length);check('默认进入大事记',read('state.view')==='facts');
read("state.query='别称检索测试'");check('按主体别称搜索',read('filtered().length')>0);read("state.query='那50万'");check('原话关键词匹配',read('filtered().length')>0);read("state.query='5600'");check('金额万元口径搜索',read('filtered().length')>0);read("state.query='BANK-A01'");check('交易编号搜索',read('filtered().length')>0);
read("state.query='';state.batch='第1批'");check('批次筛选',read('filtered().every(f=>f.citation_ids.some(r=>M[R[r].material_id].batch_id===state.batch))'));
read("state.batch='';state.category='资金资料'");check('材料类别筛选',read('filtered().length')>0);read("state.category='';state.review='需补核'");check('复核状态筛选',read('filtered().length')>0);read("state.review='';state.kind='一方陈述'");check('记录类型筛选',read('filtered().length')>0);read("state.kind='';state.material=D.materials[0].id");check('具体材料筛选',read('filtered().every(f=>f.citation_ids.some(r=>R[r].material_id===state.material))'));read("state.material='';state.subject=D.subjects[0].id");check('具体主体筛选',read('filtered().every(f=>f.subject_ids.includes(state.subject))'));
read('resetFilters();showFact(D.facts[0].id)');const selected=read('state.selected');read("state.query=D.facts[0].id;renderFacts()");check('仍可见事实详情状态保留',read('state.selected')===selected&&el('fact-detail').innerHTML.includes(selected));read("state.query='不存在的关键词';renderFacts()");check('不可见详情清除',read('state.selected')===null);
read("resetFilters();state.query='那50万';printFacts(false)");check('打印当前筛选保留原话及出处',el('print-root').innerHTML.includes('那50万')&&/R\d{4} \/ M\d{4}/.test(el('print-root').innerHTML));check('打印不改变筛选',read('state.query')==='那50万');const count=(el('print-root').innerHTML.match(/class="print-fact /g)||[]).length;check('打印筛选事实数一致',count===read('filtered().length'));read('printFacts(true)');check('打印全量', (el('print-root').innerHTML.match(/class="print-fact /g)||[]).length===data.facts.length);check('打印实际调用已触发',printed===2);
read("navigate('timeline')");check('旧timeline栏目链接兼容',read('state.view')==='facts');
read('resetFilters();openEntity(D.subjects[0].id)');check('主体关联详情',el('entity-detail').innerHTML.includes(data.subjects[0].name));read('openEntity(D.materials[0].id)');check('材料关联详情',el('entity-detail').innerHTML.includes(data.materials[0].filename));read('openEntity(D.issues[0].id)');check('待核关联详情',el('entity-detail').innerHTML.includes(data.issues[0].title));read('openEntity(D.citations[0].id)');check('引用关联详情',el('entity-detail').innerHTML.includes(data.citations[0].quote));
read('resetFilters();showFact(D.facts[0].id);D.facts[0].manual={amount:0};renderFacts()');check('人工更正0在详情呈现',el('fact-detail').innerHTML.includes('人工金额')&&el('fact-detail').innerHTML.includes('0 元'));
const ar=data.citations.find(r=>r.audio_href),audio={readyState:0,currentTime:0,events:{},addEventListener(k,f){this.events[k]=f},load(){this.loaded=true},play(){this.played=true;return Promise.resolve()}};
listeners.get('click')({target:{closest:()=>({dataset:{play:ar.id},hasAttribute:()=>false,parentElement:{querySelector:()=>audio}})}});
check('音频等待元数据后再定位',audio.loaded&&audio.currentTime===0);audio.events.loadedmetadata();check('元数据就绪定位并播放',audio.currentTime===ar.locator.start&&audio.played);
const gs=read('amountGroups()'),ret=gs.find(g=>g.transaction==='RETURN-01'&&g.role==='回款记载');check('同交易多份引用不重复组',ret&&ret.facts.length>=2&&ret.amounts.length===1);
read('D.facts[0].description="<script>mock</script>";renderFacts()');check('原文HTML转义',el('fact-list').innerHTML.includes('&lt;script&gt;mock&lt;/script&gt;')&&!el('fact-list').innerHTML.includes('<script>mock'));
check('离线无外部脚本样式',!/<(?:script|link)[^>]+(?:src|href)="https?:\/\//.test(html));check('手机和A4样式存在',html.includes('max-width:760px')&&html.includes('size:A4')&&html.includes('mobile-overlay'));check('录音定位逻辑读取引用起始秒',script.includes('a.currentTime=r.locator?.start||0')&&data.citations.some(r=>r.audio_href&&r.locator.end>r.locator.start));
read('resetFilters();state.scope="key";renderFacts()');check('重点视图仅包含人工true',read('filtered().length')===12&&read('filtered().every(f=>f.manual?.is_key===true)'));
check('重点视图数量标签',el('scope-key').textContent==='已选重点 12');read('state.layout="group";renderFacts()');check('分组计数汇总等于当前视图',read('groupedFacts(filtered()).reduce((n,g)=>n+g.rows.length,0)')===12);
check('分组内时序且未知日期单列',read('groupedFacts(orderedFacts).every(g=>g.sections.every(s=>s.rows.every((f,i)=>i===0||(s.rows[i-1].date.iso||"9999")<=(f.date.iso||"9999"))))'));
read('resetFilters();state.layout="group";renderFacts()');check('未分组置后',read('groupedFacts(filtered()).at(-1).label')==='未分组');check('分组顺序按首次出现',read('groupedFacts(filtered()).map(g=>g.label).slice(0,-1).join("|")')===read('groupOrder.join("|")'));
const baselineGroups=read('groupedFacts(filtered()).map(g=>g.label)');read('state.subject=D.subjects[0].id;renderFacts()');check('筛选不重新排列剩余分组',read('groupedFacts(filtered()).map(g=>g.label)').every((x,i,a)=>i===0||baselineGroups.indexOf(a[i-1])<baselineGroups.indexOf(x)));
read('resetFilters();state.group="g:资金往来";renderFacts()');check('常用分组筛选',read('filtered().every(f=>groupName(f)==="资金往来")')&&read('filtered().length')>0);
read('state.group="__ungrouped__";renderFacts()');check('未分组筛选',read('filtered().every(f=>!groupName(f))')&&read('filtered().length')===read('orderedFacts.filter(f=>!groupName(f)).length'));
read('resetFilters();state.query="通知轨迹";renderFacts()');check('搜索覆盖人工分组',read('filtered().every(f=>searchIndex[f.id].includes("通知轨迹"))')&&read('filtered().filter(f=>groupName(f)==="通知轨迹").length')===12);
read('resetFilters();showFact("F0007");state.scope="key";state.layout="group";renderFacts()');check('范围与布局切换保留可见详情',read('state.selected')==='F0007');
read('state.scope="all";showFact("F0001");state.scope="key";renderFacts()');check('重点视图移除非重点详情',read('state.selected')===null);
read('resetFilters();state.layout="group";state.scope="key";printFacts(false,false)');check('筛选打印沿用分组且不混入全案问题',el('print-root').innerHTML.includes('协议与主体')&&!el('print-root').innerHTML.includes('Q0005 '));
check('打印原始金额复核及分组重点标签',el('print-root').innerHTML.includes('材料金额')&&el('print-root').innerHTML.includes('重点 是')&&el('print-root').innerHTML.includes('未复核'));
read('state.query="那50万"');listeners.get('window:beforeprint')();check('重复打印刷新当前筛选范围',(el('print-root').innerHTML.match(/class="print-fact /g)||[]).length===read('filtered().length'));
read('resetFilters();showFact("F0007");closeDetails()');check('关闭详情清除选中记录',read('state.selected')===null&&!el('fact-detail').innerHTML);
check('常用和高级筛选分开',el('filters').innerHTML.includes('data-filter="group"')&&!el('filters').innerHTML.includes('data-filter="material"')&&el('advanced-filters').innerHTML.includes('data-filter="batch"'));
check('桌面六列总表和手机卡片均生成',el('fact-list').innerHTML.includes('chronicle-table')&&el('fact-list').innerHTML.includes('<th>来源</th>')&&el('fact-list').innerHTML.includes('chronicle-card'));
read('overview()');check('首页重点包含引用并保留演示声明',el('overview').innerHTML.includes('已选重点')&&el('overview').innerHTML.includes('data-open="R')&&el('overview').innerHTML.includes('演示编者人工选择'));
const audioFact=data.facts.find(f=>f.citation_ids.some(id=>data.citations.find(r=>r.id===id)?.audio_href));const audioIssue=data.issues.find(q=>!q.fact_ids.length&&q.material_ids.some(mid=>audioFact.citation_ids.some(id=>data.citations.find(r=>r.id===id)?.material_id===mid)));
read(`resetFilters();showFact('${audioFact.id}');state.query='${audioFact.id}';printFacts(false,false)`);check('录音事项详情关联按材料记录的识别疑点',el('fact-detail').innerHTML.includes(audioIssue.id));check('当前录音打印保留关联识别疑点',el('print-root').innerHTML.includes(audioIssue.id));
const empty=JSON.parse(JSON.stringify(data));for(const f of empty.facts){if(f.manual)delete f.manual.is_key}run(empty);check('无人工重点不由模型替代挑选',el('overview').innerHTML.includes('尚未人工选择重点')&&!el('overview').innerHTML.includes('mini-event'));
const large=JSON.parse(JSON.stringify(data));large.facts=Array.from({length:500},(_,i)=>({...data.facts[i%data.facts.length],id:'F'+String(9000+i)}));const start=performance.now(),c2=run(large),initialization=performance.now()-start;const timings=[];for(let i=0;i<20;i++){const t=performance.now();vm.runInContext("state.query='BANK';renderFacts()",c2,{timeout:2000});timings.push(performance.now()-t)}check('500事实检索返回正确匹配',vm.runInContext('filtered().every(f=>searchIndex[f.id].includes("bank"))',c2));

const checks=["state.query='那50万';state.scope='all'","state.query='';state.scope='key'","state.query='';state.scope='all';state.material='M0011'","state.query='';state.material='';state.layout='group'"];
const expectedCases=[large.facts.filter(f=>f.citation_ids.some(id=>data.citations.find(r=>r.id===id)?.quote.includes('那50万'))).map(f=>f.id),large.facts.filter(f=>f.manual?.is_key===true).map(f=>f.id),large.facts.filter(f=>f.citation_ids.some(id=>data.citations.find(r=>r.id===id)?.material_id==='M0011')).map(f=>f.id),large.facts.map(f=>f.id)];
for(const [i,query] of checks.entries()){vm.runInContext(query+';renderFacts()',c2);const actual=vm.runInContext('filtered().map(f=>f.id)',c2);check('500条组合筛选检查 '+i,actual.length<=500&&new Set(actual).size===actual.length&&actual.every(id=>expectedCases[i].includes(id))&&actual.length===expectedCases[i].length);}


const unusual=JSON.parse(JSON.stringify(data));unusual.facts[0].manual={chronicle_group:'__ungrouped__'};const c3=run(unusual);vm.runInContext('state.group="g:__ungrouped__";renderFacts()',c3);check('自由分组名不与未分组筛选冲突',vm.runInContext('filtered().length',c3)===1);

// Switching colors must preserve live DOM nodes, the case snapshot and playback.
const saved=new Map(),storage={getItem:k=>saved.get(k)??null,setItem:(k,v)=>saved.set(k,v)};
const themed=run(JSON.parse(JSON.stringify(data)),{storage}),themeRead=code=>vm.runInContext(code,themed);
check('首次打开默认沉稳多色',el('document-root').dataset.theme==='muted'&&el('theme-picker').value==='muted');
themeRead(`showFact('${audioFact.id}');state.query='${audioFact.id}';state.subject=D.facts.find(f=>f.id==='${audioFact.id}').subject_ids[0]||'';state.layout='group';state.printAll=false;renderFacts()`);
const beforeState=themeRead('JSON.stringify(state)'),beforeData=themeRead('JSON.stringify(D)'),beforeList=el('fact-list').innerHTML,beforeDetail=el('fact-detail').innerHTML;
const listNode=el('fact-list'),detailNode=el('fact-detail'),playingAudio={currentTime:ar.locator.start+1,paused:false};detailNode.audio=playingAudio;
for(const theme of ['bright','classic','muted']){
 el('theme-picker').events.change({target:{value:theme}});
 check('主题控件实际切换 '+theme,el('document-root').dataset.theme===theme&&el('theme-picker').value===theme&&saved.get('lugou.workpaper.theme')===theme);
 check('切换保持筛选详情数据和音频 '+theme,themeRead('JSON.stringify(state)')===beforeState&&themeRead('JSON.stringify(D)')===beforeData&&el('fact-list')===listNode&&el('fact-detail')===detailNode&&el('fact-list').innerHTML===beforeList&&el('fact-detail').innerHTML===beforeDetail&&detailNode.audio===playingAudio&&!playingAudio.paused&&playingAudio.currentTime===ar.locator.start+1);
 themeRead('printFacts(false,false)');check('切换后打印保留当前范围 '+theme,(el('print-root').innerHTML.match(/class="print-fact /g)||[]).length===themeRead('filtered().length')&&el('print-root').innerHTML.includes(audioFact.id));
}
themeRead('applyTheme("bright",true)');run(JSON.parse(JSON.stringify(data)),{storage});check('重新打开恢复已保存主题',el('document-root').dataset.theme==='bright'&&el('theme-picker').value==='bright');
saved.set('lugou.workpaper.theme','invalid-theme');run(JSON.parse(JSON.stringify(data)),{storage});check('无效保存值采用默认主题',el('document-root').dataset.theme==='muted');
const unavailable={getItem(){throw Error('unavailable')},setItem(){throw Error('unavailable')}};
const noStorage=run(JSON.parse(JSON.stringify(data)),{storage:unavailable});check('存储读取失败仍能打开底稿',el('document-root').dataset.theme==='muted'&&el('fact-list').innerHTML.includes('F0001'));
el('theme-picker').events.change({target:{value:'bright'}});check('存储写入失败仍可当页切换',el('document-root').dataset.theme==='bright'&&vm.runInContext('filtered().length',noStorage)===data.facts.length);
run(JSON.parse(JSON.stringify(data)),{storage:unavailable});check('不能保存时重新打开回到默认',el('document-root').dataset.theme==='muted');
const mobileTheme=run(JSON.parse(JSON.stringify(data)),{storage,mobile:true});vm.runInContext(`showFact('${audioFact.id}')`,mobileTheme);const mobileNode=el('mobile-detail'),mobileHTML=mobileNode.innerHTML;el('theme-picker').events.change({target:{value:'classic'}});check('手机详情在主题切换时保持原节点',el('mobile-detail')===mobileNode&&mobileNode.innerHTML===mobileHTML&&mobileHTML.includes('audio'));
const roleCards=JSON.parse(JSON.stringify(data));roleCards.case.amount_summaries=[data.case.amount_summaries[2],data.case.amount_summaries[0],data.case.amount_summaries[1]];
const roleContext=run(roleCards);const cardTones=[...el('overview').innerHTML.matchAll(/class="card amount-card" data-tone="([a-z]+)"/g)].map(m=>m[1]);
check('金额卡片换序仍按记载角色着色',cardTones.join('|')==='purple|blue|green');
check('主张拆项与未知角色分别显示',vm.runInContext('amountTone("主张拆项")==="purple"&&amountTone("其他金额")==="gold"',roleContext));
check('读取与原件复核使用不同标记并保留文字',vm.runInContext('statusTone("已提取")!==statusTone("已核对原件")&&badge("已提取").includes("已提取")&&badge("已核对原件").includes("已核对原件")',roleContext));
check('未知状态保持中性',vm.runInContext('statusTone("待律师明确")',roleContext)==='neutral');
vm.runInContext('openEntity(D.materials[0].id)',roleContext);const materialDetail=el('entity-detail').innerHTML;el('theme-picker').events.change({target:{value:'bright'}});check('关联材料详情切换后保留',el('entity-detail').innerHTML===materialDetail&&el('entity-detail').dataset.tone==='green');
vm.runInContext(`resetFilters();showFact('${audioFact.id}')`,roleContext);const playing={readyState:1,currentTime:0,play(){this.played=true;return Promise.resolve()}};el('theme-picker').events.change({target:{value:'muted'}});
listeners.get('click')({target:{closest:()=>({dataset:{play:ar.id},hasAttribute:()=>false,parentElement:{querySelector:()=>playing}})}});check('切换后录音引用仍可定位播放',playing.currentTime===ar.locator.start&&playing.played);

const stylesheet=html.match(/<style>([\s\S]*?)<\/style>/)[1],contrastResults=[];
const luminance=hex=>{const c=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c.reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0)};
for(const theme of ['muted','bright']){const block=stylesheet.match(new RegExp('html\\[data-theme="'+theme+'"\\]\\{([^}]+)\\}'))[1],colors=Object.fromEntries([...block.matchAll(/--([a-z-]+):(#\w{6})/g)].map(m=>[m[1],m[2]]));for(const name of ['blue','green','purple','gold','red','verified','neutral']){const [dark,light]=[luminance(colors[name]),luminance(colors[name+'-soft'])].sort((a,b)=>a-b),ratio=(light+.05)/(dark+.05);contrastResults.push({theme,color:name,ratio});check('主题文字与淡底对比度 '+theme+' '+name,ratio>=4.5);}}
const report={assertions:results.length,passed:results,themes:{choices:['muted','bright','classic'],default:'muted',contrast:contrastResults},pressure:{facts:500,initialization_ms:initialization,query_render_max_ms:Math.max(...timings),query_render_mean_ms:timings.reduce((a,b)=>a+b,0)/timings.length},limits:['隔离DOM替身测试，不代表真实浏览器视觉、手机裁切、打印分页或音频实际回听']};await fs.writeFile(path.join(root,'tests/web-results.local.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:results.length,themes:3,min_theme_contrast:Math.min(...contrastResults.map(x=>x.ratio)),pressure:report.pressure}));
